### ISSUE TITLE
[Federator] missing Z3 network on nodal maps

### ISSUE THREAD

**Issue by aschloem** [EIDA/userfeedback#119]
The nodal maps (RESIF, ETHZ & LMU) on www.orfeus-eu.org/data/eida/webservices/ do not show any Z3-stations, although they are accessible, e.g.:

http://erde.geophysik.uni-muenchen.de/fdsnws/station/1/query?format=text&net=Z3
http://ws.resif.fr/fdsnws/station/1/query?format=text&net=Z3

Only the ODC map (www.orfeus-eu.org/data/eida/nodes/ODC/) shows the Z3 network.

**Comment by jfclinton** [comment]
< I'm not sure this is for @damb to fix. >
I also add that the EIDA node maps on the ODC webpages above incorrectly indicate that all stations as open, when a number are actually closed.

**Comment by damb** [comment]
Thanks @aschloem for reporting.

Though, I have no insights what components are involved in order to display the stations on the maps. AFAIK, these are managed by ODC. 

CC @jbienkowski

**Comment by jbienkowski** [comment]
This is being investigated, more information will follow. Thanks for reporting this.

**Comment by jbienkowski** [comment]
Dear @aschloem,

Should be fixed now, please verify.

**Comment by aschloem** [comment]
Thank you!

**Comment by jfclinton** [comment]
Please note the issue I raised  "I also add that the EIDA node maps on the ODC webpages above incorrectly indicate that all stations as open, when a number are actually closed"
is still not fixed.
Also, currently, the KOERI node does not show any stations: http://www.orfeus-eu.org/data/eida/nodes/KOERI/

**Comment by damb** [comment]
@jfclinton, instead of collecting all bugs/problems within a single issue it is usually preferable to open dedicated issues. Thanks.


> Also, currently, the KOERI node does not show any stations: http://www.orfeus-eu.org/data/eida/nodes/KOERI/

This seems to be solved, already.
